#!/bin/bash
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
NC='\e[0m'
Y="\033[33m"
B="\033[36m"
G="\e[1;30m"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/access/main/name"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${RED} ╔═════════════════════════════════════════════════╗${NC}"
echo -e "${RED}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${NC}"
echo -e "${RED}═║${Y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${NC}${r}║═${NC}"
echo -e "${RED}═║${Y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${NC}${r}║═${NC}"
echo -e "${RED}═║${Y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${NC}${r}║═${NC}"
echo -e "${RED}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${NC}${r}║═${NC}"
echo -e "${RED} ╚═════════════════════════════════════════════════╝${NC}"
echo -e "                 ${y}INFORMASI LISENSI${NC}"                 
echo -e "${RED}═════════════════════════════════════════════════════${NC}"
echo -e "                 IP ${r}$ipsaya${NC}"
echo -e "                 ${y}PERIZINAN DITOLAK${NC}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${NC}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${NC}"
echo -e "${RED}═════════════════════════════════════════════════════${NC}"
echo -e "                 ${gb}KONTAK REGISTRASI${NC}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${NC}"
echo -e "${RED}═════════════════════════════════════════════════════${NC}"
    exit
  fi
}
checking_sc
clear
Repo1="https://raw.githubusercontent.com/DevilsTunnels/access/main/"
export MYIP=$( curl -s https://ipinfo.io/ip/ )
SELLER=$(curl -sS ${Repo1}name | grep $MYIP | awk '{print $2}')
Exp100=$(curl -sS ${Repo1}name | grep $MYIP | awk '{print $3}')
data_ip="https://raw.githubusercontent.com/DevilsTunnels/access/main/name"
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$(( ($d1 - $d2) / 86400 ))

#########################
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
# COLOR VALIDATION
clear
OR='\033[1;93m'
c="\033[0;36m" #biruterang
g="\e[92;1m"
r="\033[1;31m"  #REDTERANG
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
yell='\e[33m'
BGX="\033[42m"
END='\e[0m'
AKTIF="VERIFIED"
TOKEN="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"
REPO="https://github.com/DevilsTunnels/access.git"
EMAIL="csordervpn@gmail.com"
USER="DevilsTunnels"


add-ip() {
TIMES="10"
CHATID="-1001872029038"
KEY="6453249147:AAHKMBfdpk6SoQTB3UQS5dR9iUqi5SVTIfc"
URL="https://api.telegram.org/bot$KEY/sendMessage"


    today=`date -d "0 days" +"%Y-%m-%d"`
    git clone ${REPO} /root/access/ &> /dev/null
    clear
    echo -e "MASUKAN IP VPS YANG BELUM DI DAFTAR !"
    echo -e ""
    read -p "Input IP Address : " ip
    CLIENT_EXISTS=$(grep -w $ip /root/access/name | wc -l)
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
    echo "IP Already Exist !"
    exit 0
    fi
    echo -e ""
   # read -p "  Input Username IP (Example : croot) : " name
    name=H6EFctYeZ3DqOWSai`</dev/urandom tr -dc A-Z0-9 | head -c4`
    echo -e ""
    clear
    echo -e " ${r} How Much Days Do You Want ?${NC}"
    echo -e "  ${OR} 1.${NC}${c} 30 Days${NC}"
    echo -e "  ${OR} 2.${NC}${c} 60 Days${NC}"
    echo -e "  ${OR} 3.${NC}${c} 90 Days${NC}"
    echo -e "  ${OR} 4.${NC}${c} Lifetime${NC}"
    echo -e "  ${OR} 5.${NC}${c} Custom Expiration Date${NC}"
    echo -e ""
    read -p "Select Number 1 - 5 : " exp
    
    if [[ ${exp} == '1' ]]; then
    exp2=`date -d "30 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/access/name
    elif [[ ${exp} == '2' ]]; then
    exp2=`date -d "60 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/access/name
    elif [[ ${exp} == '3' ]]; then
    exp2=`date -d "90 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/access/name
    elif [[ ${exp} == '4' ]]; then
    exp2=`date -d "360 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/access/name
    elif [[ ${exp} == '5' ]]; then
    read -p "Input Expired Days : " exp11
    exp2=`date -d "$exp11 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/access/name
    fi
    cd /root/access
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/DevilsTunnels/access/name
    git push -f https://${TOKEN}@github.com/DevilsTunnels/access.git &> /dev/null
    rm -rf /root/access
    clear
    sleep 1
    echo "  Registering IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT="
<code>───────────────────────────</code>
<code>    SUCCES  REGISTERED IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ip</code>
<code>Registered On  : $today</code>
<code>Expired On     : $exp2</code>
<code>───────────────────────────</code>
"
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e " $COLBG1          ${WH}⇱ SUCCES ADD IP VPS ⇲           $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
    echo -e "${OR}> USERNAME   :${NC}${yell} $name"
    echo -e "${OR}> IP ADDRESS :${NC}${yell} $ip"
    echo -e "${OR}> REGISTERED :${NC}${yell} $today"
    echo -e "${OR}> EXPIRED ON :${NC}${yell} $exp2"
echo -e "$COLOR1════════════════════════════════════════════$NC"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

del-ip() {
TIMES="10"
CHATID="-1001872029038"
KEY="6453249147:AAHKMBfdpk6SoQTB3UQS5dR9iUqi5SVTIfc"
URL="https://api.telegram.org/bot$KEY/sendMessage"

    rm -rf /root/access
    git clone ${REPO} /root/access/ &> /dev/null
    clear
    echo ""
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e " $COLBG1              ${WH}⇱ LIST IP VPS ⇲             $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
grep -E "^###" "/root/access/name" | cut -d ' ' -f 2-4 | column -t | sort | uniq
echo -e "$COLOR1════════════════════════════════════════════$NC"

    read -p "Input IP Address To Delete : " ipdel
    name=$(cat /root/access/name | grep $ipdel | awk '{print $2}')
    exp=$(cat /root/access/name | grep $ipdel | awk '{print $3}')
    if [[ ${exp} == 'Lifetime' ]]; then
    sed -i "/^### $name $exp $ipdel/,/^},{/d" /root/access/name
    fi
    cd /root/access/name
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/DevilsTunnels/access
    git push -f https://${TOKEN}@github.com/DevilsTunnels/access.git &> /dev/null
    rm -rf /root/access
    clear
    sleep 1
    echo "  Delete IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT1="
<code>───────────────────────────</code>
<code>    SUCCES DELETE  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp</code>
<code>───────────────────────────</code>
"
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e " $COLBG1          ${WH}⇱ DONE DELETE IP VPS ⇲          $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
    echo -e "${OR}> USERNAME   :${NC}${yell} $name"
    echo -e "${OR}> IP ADDRESS :${NC}${yell} $ipdel"
    echo -e "${OR}> EXPIRED ON :${NC}${yell} $exp"
echo -e "$COLOR1════════════════════════════════════════════$NC"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT1&parse_mode=html" $URL >/dev/null
}

renew-ip() {
TIMES="10"
CHATID="-1001872029038"
KEY="6453249147:AAHKMBfdpk6SoQTB3UQS5dR9iUqi5SVTIfc"
URL="https://api.telegram.org/bot$KEY/sendMessage"

    rm -rf /root/access
    git clone ${REPO} /root/access/ &> /dev/null
    clear
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e " $COLBG1            ${WH}⇱ RENEW IP VPS ⇲              $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
    grep -E "^###" "/root/access/name" | cut -d ' ' -f 2-4 | column -t | sort | uniq
echo -e "$COLOR1════════════════════════════════════════════$NC"
    echo ""
    read -p "  Input IP Address To Renew : " ipdel
    read -p "  Input Days  : " days
    name=$(cat /root/access/name | grep $ipdel | awk '{print $2}')
    exp=$(cat /root/access/name | grep $ipdel | awk '{print $3}')
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $days))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "s/### $name $exp $ipdel/### $name $exp4 $ipdel/g" /root/access/name
    cd /root/access
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/DevilsTunnels/access
    git push -f https://${TOKEN}@github.com/DevilsTunnels/access.git &> /dev/null
    rm -rf /root/access
    clear
    sleep 1
    echo "  Renew IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT2="
<code>───────────────────────────</code>
<code>    SUCCES RENEW  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp4</code>
<code>───────────────────────────</code>
"
    echo ""
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e " $COLBG1            ${WH}⇱ RENEW IP VPS ⇲              $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
    echo -e "${OR}> USERNAME   :${NC}${yell} $name"
    echo -e "${OR}> IP ADDRESS :${NC}${yell} $ipdel"
    echo -e "${OR}> EXPIRED ON :${NC}${yell} $exp4"
echo -e "$COLOR ════════════════════════════════════════════$NC"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}

clear
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e " $COLBG1            ${WH}⇱ MENU RESSELER IP ⇲          $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
echo -e "$COLOR1║$NC$r NAME RESSELER   :$NC $SELLER"
echo -e "$COLOR1║$NC$r STATUS RESSELER :$NC $AKTIF"
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e "$COLOR1║${NC}${g} 1.$NC ${c}ADD IP RESSELER $NC"     
echo -e "$COLOR1║${NC}${g} 2.$NC ${c}DELETE IP RESSELER $NC"
echo -e "$COLOR1║${NC}${g} 3.$NC ${c}RENEW IP RESSELER $NC"
echo -e "$COLOR1║${NC}${g} 4.$NC ${c}BACK TO MENU $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
echo ""
read -p " Select From Options : " menu
case $menu in
1 | 01)
clear
add-ip
;;
2 | 02)
clear
del-ip
;;
3 | 03)
clear
renew-ip
;;
4 | 04)
menu
;;
*)
exit
;;
esac